package genpact.bank.transactions.services;

import org.springframework.stereotype.Service;

import genpact.bank.transactions.entities.Transaction;
import genpact.bank.transactions.repositories.TransactionDao;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Random;

@Service
public class TransactionServiceImpl implements TransactionService {

	private final TransactionDao transactionDao;

	public TransactionServiceImpl(TransactionDao transactionDao) {
		this.transactionDao = transactionDao;
	}

	@Override
	public List<Transaction> getAllTransactions() {
		return transactionDao.getAllTransactions();
	}

	@Override
	public Transaction getTransactionById(Integer transactionId) {
		return transactionDao.getTransactionById(transactionId);
	}

	@Override
	public void addTransaction(Transaction transaction) {
	    // Generate a unique reference number with prefix "UTR"
	    String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("HHmmss"));
	    int randomNumber = new Random().nextInt(90000) + 10000; // Generate a 5-digit random number
	    String uniqueReferenceNumber = "UTR" + timestamp + randomNumber;

	    // Set the autogenerated reference number
	    transaction.setReferenceNumber(uniqueReferenceNumber);

	    // Persist the transaction
	    transactionDao.addTransaction(transaction);
	}

	@Override
	public void updateTransaction(Transaction transaction) {
		transactionDao.updateTransaction(transaction);
	}

	@Override
	public void deleteTransaction(Integer transactionId) {
		transactionDao.deleteTransaction(transactionId);
	}

	@Override
	public Transaction getTransactionByRef(String referenceNumber) {
		// TODO Auto-generated method stub
		return transactionDao.getTransactionByRefId(referenceNumber);
	}

	@Override
	public List<Transaction> getTransactionsByAccountId(int accountId) {
		return transactionDao.getTransactionByAccountId(accountId);
	}

	@Override
	public List<Transaction> getBranchTransactions(int branchId) {
		
		return transactionDao.getBranchTransaction(branchId);
	}
}